# Generated by Django 4.2.4 on 2023-08-08 18:39

from django.db import migrations, models
import job.models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=job.models.image_upload
            ),
        ),
    ]
