# Generated by Django 4.2.4 on 2023-08-09 11:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0002_alter_job_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="address",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
